config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'billboards#index'

  resources :billboards

  resources :artists do
    resources :songs
  end

  get 'new_billboard_song:id', to: 'billboards#new_song', as: 'new_billboard_song'
  post 'add_billboard_song/:id/:song_id', to: 'billboards#add_song', as: 'add_billboard_song'
  delete 'remove_billboard_song/:id/:song_id', to: 'billboards#remove_song', as: 'remove_billboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :user

  has_many :songs, dependent: :destroy
  has_many :billboards, through: :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  belongs_to :user
  has_many :songs, dependent: :destroy
  has_many :artists, through: :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard, optional: true
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :billboards
  has_many :artists
  has_many :songs, through: :artists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  def index
    @artists = current_user.artists
  end

  def new
    @artist = current_user.artists.new
  end

  def create
    @artist = current_user.artists.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      redirect_to artists_path
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

  def set_user
  end

  def set_artist
    @artist = current_user.artists.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :genre)
  end
  def set_user

  end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy, :remove_song]

  def index
    @billboards = current_user.billboards
  end

  def new
    @billboard = current_user.billboards.new
  end

  def create
    @billboard = current_user.billboards.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def show
    @songs = @billboard.songs
  end

  def edit
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboards_path
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  def new_song
    @billboard = Billboard.find(params[:id])
    @songs = Song.all.where(billboard_id: nil)
  end

  def add_song
    @billboard = Billboard.find(params[:id])
    @billboard.songs << Song.find(params[:song_id])
    redirect_to billboard_path(@billboard)
  end

  def remove_song
    Song.find(params[:song_id]).update(billboard_id: nil)
    redirect_to billboard_path(@billboard)
  end

  private

  def set_billboard
    @billboard = current_user.billboards.find(params[:id])
  end

  def billboard_params
    params.require(:billboard).permit(:name, :region, :song_id, :artist_id)
  end

end

app/controllers/songs_controller.rb
# frozen_string_literal: true

class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:edit, :update, :destroy, :show]
  def index
    @songs = @artist.songs
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_songs_path(@artist)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @song.update(song_params)
      redirect_to artist_songs_path(@artist)
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_songs_path
  end

  def show; end

  def new_song
    @billboard = Billboard.find(params[:billboard_id])
    @songs = Song.all.find(params[:id])
  end

  def add_song
    @billboard = Billboard.find(params[:billboard_id])
    @billboard.songs << Song.find(params[:id])
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def song_params
    params.require(:song).permit(:name, :bpm)
  end

  def set_song
    @song = Song.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: @artist, local: true) do |f| %>
<div class='field'>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, focus: true %>
</div>
<div class='field'>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
</div>
<%= f.submit %>
<% end %>
<%= link_to 'Go Back', artists_path %>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<%= render 'form' %>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<%= link_to "Add New Artist", new_artist_path %>
<hr / />
<% @artists.each do |artist| %>
  <h3><%= link_to "#{artist.name}", artist_songs_path(artist) %></h3>
  <h6> <%= artist.genre %> </h6>
  <%= link_to "edit", edit_artist_path(artist) %>
  <%= link_to "delete", artist_path(artist), method: :delete %>
  <br />
<% end %>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<%= render 'form' %>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/billboards/_billboard_form.html.erb
<% current_user.billboards.each do |billboard| %>
    <%= link_to "Add to #{billboard.name} - #{billboard.region}",  new_billboard_song_path(billboard, @id.id) %>

  <% end %>

app/views/billboards/_form.html.erb
<%= form_with(model: @billboard, local: true) do |f| %>
<div class='field'>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, focus: true %>
</div>
<div class='field'>
  <%= f.label 'Region/Type' %>
  <%= f.text_field :region %>
</div>
<%= f.submit %>
<% end %>
<%= link_to 'Go Back', billboards_path %>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<%= render 'form' %>

app/views/billboards/index.html.erb
<h1>Billboards#index</h1>
<%= link_to "New Billboard", new_billboard_path %>
<hr / />
<% @billboards.each do |billboard| %>
  <h3><%= link_to "#{billboard.name} - #{billboard.region}", billboard_path(billboard) %></h3>
  <%= link_to "edit", edit_billboard_path(billboard) %>
  <%= link_to "delete", billboard_path(billboard), method: :delete %>
  <br />
<% end %>

app/views/billboards/new.html.erb
<h1>Billboards#new</h1>
<%= render 'form' %>

app/views/billboards/new_song.html.erb
<h2>Add a song to the <% "#{@billboard.name}"%> chart</h2>
<%= link_to 'Go Back', billboards_path %>

<% @songs.each do |song| %>
  <li>
    <%= link_to song.name, add_billboard_song_path(@billboard, song), method: :post %>
  </li>
  <hr />
<% end %>

app/views/billboards/show.html.erb
<h3><%= link_to "Back to all Billboards", billboards_path %></h3>
  <h3><%= link_to "Edit Billboard", edit_billboard_path %></h3>
  <%# <!-- <h3><%= link_to "Delete Billboard", billboard_path(@billboard), method: :delete %>
<h1> <%= @billboard.name %></h1>
  <%= link_to 'Add song to charts!', new_billboard_song_path(@billboard) %>
    <% if @songs.any? %>
    <% @songs.each_with_index do |song, index| %>
      <li><%= "#{index+1}: #{song.name}"%>
      <ul>
        <li><%= "by: #{song.artist.name}" %></li>
        <li>
          <%= link_to 'Get it off the charts', remove_billboard_path(@billboard, song), method: :delete %></li>
          </li>
      </ul>
    <% end %>
  <% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
    <a href="#" class="brand-logo">
      <%= link_to image_tag('billboard.png'), root_path %>
    </a>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li>
          <%= link_to "artists", artists_path, :class => "btn btn-danger navbar-btn"%>
        </li>
        <li>
          <%= link_to "logout", destroy_user_session_path, method: :delete, :class => "btn btn-default"%>
        </li>
      <% else %>
        <li>
          <%= link_to 'login', new_user_session_path, :class => "btn btn-default"%>
        </li>
        <li>
          <%= link_to 'sign up', new_user_registration_path, :class => "btn btn-danger navbar-btn" %>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardPlus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_smart_backlink.html.erb
# views/shared/_smart_backlink.html.erb
<% paths = session[:paths_visited] %>
<% path_index = paths.index(@path_name) %>
<div class="body--padding">
  <%= link_to 'Back', paths[path_index - 1] if not current_page?(dashboard_path)  %>
</div>

app/views/songs/_form.html.erb
<%= form_with(model: [@artist, @song], local:true) do |f| %>
  <div class='field'>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, focus: true %>
  </div>
  <div class='field'>
    <%= f.label :bpm %>
    <%= f.number_field :bpm %>
  </div>
  <%= f.submit %>
<% end %>

<%= link_to 'Go back', artist_songs_path(@artist) %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>
<%= render 'form' %>

app/views/songs/index.html.erb
<h1><%= @artist.name %></h1>
<%= link_to 'Add new song', new_artist_song_path(@artist) %>
<% @artist.songs.each do |song| %>
  <h4><%= song.name %></h4>
  <h6>BPM:<%= song.bpm %></h6>
  <%= link_to 'edit', edit_artist_song_path(@artist, song) %>
  <%= link_to 'delete', artist_song_path(@artist, song), method: :delete %>
<% end %>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<%= link_to 'Add new song', new_artist_song_path(@artist) %>
<% @artist.songs.each do |songs| %>
<h4><%= song.name %></h4>
<h6><%= song.bpm %></h6>
<%= link_to 'edit', edit_artist_song_path(@artist, song) %>
<%= link_to 'delete', artist_song_path(@artist, song), method: :delete %>
<% end %>